secrets: 
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt

networks:
  app-network:
    driver: bridge

volumes: 
  db_data:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql
    environment:
      #MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_ROOT_PASSWORD: strong_root_password
      MYSQL_DATABASE: semainedb
      MYSQL_USER: semaineuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    ports:
      - "3306:3306"

  backend:
    image: python:3.12.0
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    build:
      context: ./myapp
      dockerfile: dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: project.settings 
      DATABASE_HOST: database
      DATABASE_USER: semaineuser
      DATABASE_NAME: semainedb
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password 
    ports:
      - "8000:8000"
    secrets:
      - mysql_root_password  

    networks:
      - app-network

  front:
    image: tiangolo/uwsgi-nginx:python3.8

    volumes:
      - ./myapp/templates:/usr/src/app
    networks:
      - app-network
