secrets: 
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt

networks:
  app-network:
    driver: bridge

volumes: 
  db_data:

services:

  database:
      image: mysql
      environment:
        #MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        MYSQL_ROOT_PASSWORD: strong_root_password
        MYSQL_DATABASE: semainedb
        MYSQL_USER: semaineuser
        MYSQL_PASSWORD: strong_user_password
      secrets:
        - mysql_root_password
        - mysql_user_password
      volumes:
        - db_data:/var/lib/mysql
        - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql 

      networks:
        - app-network
      ports:
        - "3306:3306"
      restart: always 
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    networks:
      - app-network
  
  backend:
    image: python:3.12.0
    depends_on:
      database:
        condition: service_healthy
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    build:
      context: ./myapp
      dockerfile: dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: project.settings 
      DATABASE_HOST: database
      DATABASE_USER: semaineuser
      DATABASE_NAME: semainedb
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password 
    ports:
      - "8000:8000"
    secrets:
      - mysql_root_password  
    networks:
      - app-network
    restart: always
